- charts/devices-api/templates/cronjob.yaml
- charts/devices-api/values-prod.yaml
- remove smartcar sync (this command does not exist anymore, would likely cause problems running it)
- rename cronjob stuff to make more sense
- run valuations pull once a month
> PLA-837 update cronjob to pull valuations once a month

- cmd/devices-api/api.go
- internal/controllers/device_data_controller.go
- internal/controllers/device_data_controller_test.go
- sort the user_device_data by odometer asc so that when merging data from autopi and smartcar, even if smartcar data says it is newer we actually use the newest data, which is determined by the highest odometer
`/user/devices/{udid}/status`
> PLA-1033 prioritize by odometer for device status

- internal/controllers/device_data_controller.go
- internal/controllers/device_data_controller_test.go
The range in user_device_data.data comes from the ingest. It is only present from SmartCar connected vehicles. Thanks to having fuel tank size and mpg for many vehicles, we can calculate this after the fact. 
If range in data is empty, then calculate on the fly using current fuel percent remaining - this should show range for many autopi customers. 
`/user/devices/:userDeviceID/status`
> PLA-1054 add range calculation if it is not in data from ingest

- cmd/devices-api/api.go
- internal/controllers/device_data_controller_test.go
- internal/controllers/user_devices_controller.go
- internal/controllers/user_devices_controller_test.go
- internal/controllers/user_integrations_controller.go
- internal/controllers/user_integrations_controller_test.go
Problem we were having is that when the smartcar user device is created on the fly by decoding the VIN from the first endpoint, `/fromsmartcar` the exchangeToken api call to SC is already done, therefore it can't be done again in the subsequent register integration request. 
Solution is to cache the token in redis, encrypted, and then on the register integration request we check if it is in the cache and pull it out. 
Idea has been to maintain this operation in two endpoints, so as not to break existing clients. There could be an optimization here where we create the user device and the integration all in the first endpoint, but that would break the standardized flow we have created and also make SC more special case.
> PLA-1104 smartcar cache token btw add from vin and register integration

- cmd/devices-api/api.go
- internal/config/settings.go
- internal/controllers/device_data_controller_test.go
- internal/controllers/geofences_controller_test.go
- internal/controllers/helpers/handlers.go
- internal/controllers/user_devices_controller.go
- internal/controllers/user_devices_controller_test.go
- internal/controllers/user_integrations_controller.go
- internal/controllers/user_integrations_controller_test.go
- internal/controllers/webhooks_controller_test.go
- internal/services/autopi/integration_test.go
- internal/services/autopi_api_service_test.go
- internal/services/device_status_ingest_service_test.go
- internal/test/helpers.go
- user id in redis cache key
- duplicate vin check
> PLA-1118 close loopholes in /fromsmartcar endpoint

- internal/controllers/user_devices_controller.go
- internal/controllers/user_devices_controller_test.go
- we want to make sure a device_integration record gets created - fine if it already exists, when a vin is added via the endpoint that is called as part of the autopi initial pairing.
> PLA-1330 create device_integration on decoding vin from autopi

- internal/controllers/user_devices_controller.go
- internal/controllers/user_devices_controller_test.go
- internal/services/autopi/integration_test.go
- internal/test/helpers.go
- adjust `/user/devices/me` endpoint to include vehicles that are owned by the user's eth address, taking care to not double-show vehicles
> PLA-1316-devices-owned-by-addr

- cmd/devices-api/main.go
- cmd/devices-api/temp_fix_signal_timestamps.go
- internal/controllers/device_data_controller.go
- internal/controllers/device_data_controller_test.go
- internal/controllers/nft_controller.go
- internal/controllers/user_devices_controller.go
- internal/services/device_status_ingest_service.go
- internal/services/device_status_ingest_service_test.go
- leverage the new signals column to better merge data so that we pick the most recent at a signal level
- with odometer specifically, always take the bigger number
- fix ingest when writing timestamp to set utc 0 (add Z char)
- add a script to fix the timestamps on existing data
`.../status`
- run the data fix as soon as this deploys
> PLA-1411 Merge data based on timestamp

- internal/controllers/device_data_controller.go
- internal/controllers/nft_controller.go
if people had multiple integrations, with one of them being very stale data, this would cause nothing to return b/c the didn't have anything in the signals column. Instead we do a query level filter for must all return with signals and be newer than 2 weeks as well.
> PLA-1425 Avoid bug when signals was null from stale data and filter for > 2 weeks

- charts/devices-api/values-prod.yaml
- charts/devices-api/values.yaml
- internal/controllers/synthetic_devices_controller.go
- internal/controllers/synthetic_devices_controller_test.go
Little notes
* Error handling could be better
* Used the assertion methods directly on the suite, that's kinda neat
* Was more specific in checking arguments to the mocks
> Save Smartcar external id and available endpoints

- cmd/devices-api/main.go
- cmd/devices-api/populate_powertrain.go
- internal/controllers/user_devices_controller.go
- internal/controllers/user_devices_controller_test.go
- internal/services/device_definitions_service.go
- internal/services/mocks/device_definitions_service_mock.go
- internal/test/helpers.go
> PRO-1800 - set powertrain from device definition

- cmd/devices-api/api.go
- cmd/devices-api/main.go
- internal/services/contracts_events_consumer.go
- internal/services/contracts_events_consumer_test.go
- internal/services/registry/storage.go
> Try to move to listening for unpair

- cmd/devices-api/populate_powertrain.go
> SM-2 update powertrain script with prompt

- internal/services/issuer/verifiable_credential.go
- internal/services/issuer/verifiable_credential_test.go
- internal/services/issuer/w3c_2018_credentials_v1.json
- attempting to solve: `loading remote context failed: Dereferencing a URL did not result in a valid JSON-LD context: https://www.w3.org/2018/credentials/v1`
- preload using embed 
- do we want to break this out into a separate VC service?
> SI-2176-preload-jsonld-vc-issuer

- internal/controllers/helpers/handlers.go
- internal/controllers/user_integrations_controller.go
We could use a more comprehensive treatment of this
> Fiber-friendly error when /unpair gets a signature of length 0

- cmd/devices-api/main.go
- cmd/devices-api/remake_user_device_token_table.go
Loads everything in vehicle_nfts with user_device_id and token_id populated. Sends the mapping CloudEvents into table.device.token.mapping
> Add subcommand remake-user-device-token-table

- internal/contracts/registry.go
- internal/services/contracts_events_consumer.go
- internal/services/contracts_events_consumer_test.go
- internal/services/fingerprint/consumer_test.go
When an AftermarketDeviceAddressReset event is received, update the 0x address of the device to reflect the change
- ethereum_address is a primary key in the aftermarket_devices table so this deletes the record and re-inserts it
- regenerated registry.go
> SI-2213-amd-addr-reset-event

- internal/rpc/user_devices.go
- internal/services/smart_car_api_service_test.go
- Throw error when decoding a VIN and its year is older than 2008
> [SM-395] don't allow vins older than 2008

- cmd/devices-api/update_autopi_state.go
- internal/controllers/webhooks_controller.go
- internal/controllers/webhooks_controller_test.go
- internal/services/autopi_api_service.go
- internal/services/mocks/autopi_api_service_mock.go
When updating device state in AP user metadata (used for troubleshooting), also set the region/country for them to use for load balancing.
> SM-374 AutoPi user device metadata setting for Country and Region

- go.mod
- go.sum
- internal/controllers/device_data_controller.go
- internal/controllers/geofences_controller.go
- internal/controllers/helpers/handlers.go
- internal/controllers/nft_controller.go
- internal/controllers/synthetic_devices_controller.go
- internal/controllers/synthetic_devices_controller_test.go
- internal/controllers/user_devices_controller.go
- internal/controllers/user_devices_controller_test.go
- internal/controllers/user_integrations_controller.go
- internal/middleware/owner/owner.go
Showing the actual error to users when decode issues will help support them more quickly.
- use GrpcToFiberErr when get an error decoding a VIN
- remove local version of GrpcToFiberErr and use shared one everywhere
> SM-392: do not opaque the err when decoding VIN

- charts/devices-api/values-prod.yaml
- charts/devices-api/values.yaml
- cmd/devices-api/api.go
- internal/config/settings.go
- internal/controllers/user_devices_controller.go
- internal/controllers/user_devices_controller_test.go
- internal/controllers/user_integrations_auth_controller.go
- internal/controllers/user_integrations_auth_controller_test.go
- internal/controllers/user_integrations_controller.go
- internal/services/mocks/nats_service_mock.go
- internal/services/models.go
- internal/services/nats_service.go
- Add instant offer request models
- add instant offer request queue data
- request instant offer
> [SM-548] add instant offer request

- internal/controllers/user_integrations_controller.go
- internal/services/contracts_events_consumer.go
when compiling vehicles to be burned, there were a few that were not associated with a user device id but were paired on chain. seems like the event was never fully processed. adding these logs so that if this happens in the future we can more easily triangulate where the problem is occurring
> logging-aftermarketDevicePaired

- charts/devices-api/values-prod.yaml
- charts/devices-api/values.yaml
- internal/config/settings.go
- internal/services/contracts_events_consumer.go
- internal/services/contracts_events_consumer_test.go
- internal/services/registry/storage.go
* Longer variable names, more and more standardized logging
* Handle synthetic burns as contract events
* Merge the two contract event handlers handling vehicle burning
> Clean up metatransaction handling

- .github/workflows/lint.yml
- charts/devices-api/values.yaml
- internal/config/settings.go
- internal/controllers/geofences_controller.go
- internal/controllers/geofences_controller_test.go
We already emit privacy fence updates to `table.device.privacyfence`, keyed by user device id, when a fence is modified or when a fence is attached to or detached from a vehicle. Here we also emit the same messages to `table.device.privacyfence.v2`, keyed by vehicle token id.
Asides
* You can't attach or detach a fence from a vehicle that isn't minted.
* Fixes a [long-standing bug](https://github.com/DIMO-Network/devices-api/pull/356/files#diff-363f4238e0f752e79e0a6f611107a294ae1e44b37ee93c2d1705216563c96c66L332): anyone could attach a privacy fence they own to any vehicle, even one they did not own.
Downsides
* If you have an un-minted vehicle that already has fences attached (under the old controller), and you later mint it, we don't emit updates.
I want to clean this file up more, but …
> SI-2726 Emit privacy zones by vehicle id

- cmd/devices-api/main.go
- cmd/devices-api/populate_privacy_v2_topic.go
Add a subcommand `devices-api populate-privacy-topic-v2`. Sends out privacy zones from #356 keyed by token id.
> SI-2726 NFT privacy zones backfill

- internal/services/autopi_api_service.go
- internal/services/autopi_api_service_test.go
- internal/services/testDongleDeviceResp.json
- get the existing metadata and only set properties ifwe have them
> SM-716 fix autopi update state clearing existing metadata

- cmd/devices-api/sync_device_templates.go
limit templates for being moved for autopi's in certain special case templates, eg. j1939 and obd off
> SM-779 do not allow moving certain existing templates during batch sync

- docs/docs.go
- docs/swagger.json
- docs/swagger.yaml
- internal/controllers/nft_controller.go
- internal/controllers/nft_controller_test.go
- internal/controllers/user_devices_controller.go
In new pairing flow this is the only place we could set the country code and protocol, so adding it here
> VIN patch endpoint add set the country code and protocol

- charts/devices-api/values-prod.yaml
- charts/devices-api/values.yaml
- internal/config/settings.go
- internal/controllers/user_integrations_auth_controller.go
- internal/controllers/user_integrations_auth_controller_test.go
We previously hard-coded our demand for the Tesla `vehicle_device_data` scope, which gave us the telemetry data in which we were interested. [They announced on November 26](https://developer.tesla.com/docs/fleet-api/announcements#2024-11-26-introducing-a-new-oauth-scope-vehicle-location) that we now need `vehicle_location` to get latitude and longitude.
@adityap92 wants to test this out in the development environment, so here we make the required scopes a setting, `TESLA_REQUIRED_SCOPES`.
> EX-3182 Make required Tesla scopes a setting

- internal/controllers/user_devices_controller.go
- internal/controllers/user_integrations_controller.go
- /fromsmartcar endpoint does all the work
- no need to call register integration endpoint
- tests have not been updated
- tried to do it without modifying much code
> Smartcar onboarding try single call

- cmd/devices-api/main.go
- cmd/devices-api/smartcar_stop_connections.go
- deal with scammer connections or just poor data connections
- note this just stops the polling job and sets status to authfailure, does not call SC api to delete the connection by vehicle_id
> Add script to disconnect / stop smartcar connections

- internal/controllers/user_integrations_controller.go
- internal/controllers/user_integrations_controller_test.go
- internal/rpc/tesla.go
- internal/services/mocks/tesla_fleet_api_service_mock.go
- internal/services/tesla_fleet_api_service.go
The key_paired field is simply wrong when you use id
> Use VIN instead of Tesla numeric id when checking Telemetry status

- charts/devices-api/values-prod.yaml
- charts/devices-api/values.yaml
- internal/config/settings.go
- internal/controllers/user_devices_controller.go
Added a (hopefully short-lived) setting `ENABLE_SACD_MINT`. True on dev, false on prod.
> Ex 3565 combined vehiclesacd minting not deployed

- go.mod
- go.sum
- internal/controllers/user_integrations_auth_controller.go
- internal/controllers/user_integrations_auth_controller_test.go
main advantage of doing this is that the definition will get created if it doesn't exist
underlying logic in DD-api has been changed to not decode with a vendor but just use same logic as had here, so failure rate should be much lower.
> Decode Tesla VINs with DD-api

- internal/config/settings.go
- internal/controllers/synthetic_devices_controller.go
- internal/controllers/user_devices_controller.go
New boolean setting `BLOCK_MINTING`. Turns off
- `POST /v1/user/devices/{userDeviceId}/commands/mint`
- `POST /v1/user/devices/{userDeviceId}/integrations/{integrationId}/mint`
> Setting for blocking minting

- internal/controllers/user_integrations_controller.go
This started populating for older, incapable cars
> Remove fleet_telemetry_version check
