DIMO-Network/devices-api

cmd/devices-api/load_valuations.go
internal/services/device_definitions_service.go
internal/services/device_status_ingest_service_test.go
internal/services/mocks/device_definitions_service_mock.go

PLA-423 cleanup, logging, country logic

---

cmd/devices-api/autopi_tools.go
internal/controllers/documents_controller.go
internal/controllers/user_integrations_controller.go
internal/services/autopi_api_service.go
internal/services/mocks/autopi_api_service_mock.go
internal/services/task_status_listener_test.go

autopi tools: Autopi template add pids

---

internal/services/autopi_api_service.go

CS-276 change per recommendation

---

internal/controllers/documents_controller.go

Remove S3 down/up managers

---

internal/controllers/user_devices_controller.go
internal/controllers/user_devices_controller_test.go

PLA-1069 : add logic to create smartcar integration on device definition on decode

---

cmd/devices-api/autopi_tools.go
cmd/devices-api/generate_events.go
cmd/devices-api/individual_kafka_task.go
cmd/devices-api/load_valuations.go
cmd/devices-api/main.go
cmd/devices-api/migrate.go
cmd/devices-api/populate_es_dd_data.go
cmd/devices-api/populate_es_region_data.go
cmd/devices-api/populate_powertrain.go
cmd/devices-api/remake_autopi_topic.go
cmd/devices-api/remake_device_definition_topics.go
cmd/devices-api/remake_fence_topic.go
cmd/devices-api/remake_smartcar_topic.go
cmd/devices-api/set_command_compat.go
cmd/devices-api/start_smartcar.go
cmd/devices-api/sync_device_templates.go
cmd/devices-api/update_autopi_state.go
cmd/devices-api/web2_pair_sub_command.go
go.mod
go.sum

PLA-1029 - Implement sub-commands

---

cmd/devices-api/dependency_injection.go
cmd/devices-api/generate_events.go
cmd/devices-api/individual_kafka_task.go
cmd/devices-api/main.go
cmd/devices-api/remake_autopi_topic.go
cmd/devices-api/remake_device_definition_topics.go
cmd/devices-api/remake_fence_topic.go
cmd/devices-api/remake_smartcar_topic.go
cmd/devices-api/set_command_compat.go
cmd/devices-api/start_smartcar.go
cmd/devices-api/web2_pair_sub_command.go
internal/controllers/device_data_controller_test.go

Implement sub-commands with di

---

internal/services/device_status_ingest_service.go

Only update AutoPi’s statuses for AutoPis

---

internal/controllers/device_data_controller.go
internal/controllers/device_data_controller_test.go
internal/services/mocks/openai_service_mock.go
internal/services/openai.go

PLA-1156 Remove year from ChatGPT query and update tests

---

migrations/20230313102015_error_code_queries.sql
migrations/20230322050933_modify_error_codes_constraint.sql

PLA-1158 Add cascade delete to error codes

---

cmd/devices-api/api.go
internal/api/user_devices.go

PLA-1116 - GRPC endpoint implementation

---

charts/devices-api/values-prod.yaml
charts/devices-api/values.yaml
internal/config/settings.go
internal/contracts/AftermarketDeviceId.go
internal/contracts/aftermarket_device_id.go
internal/services/contracts_events_consumer.go
internal/services/contracts_events_consumer_test.go
internal/services/utilities.go

PLA-1159 - aftermarket device transfer

---

cmd/devices-api/autopi_clear_vin.go
cmd/devices-api/autopi_tools.go
cmd/devices-api/main.go
internal/services/autopi_api_service.go

clear vin from autopi for our known units

PLA-1271 clear vin on autopi

---

internal/controllers/nft_controller.go

Aftermarket NFT mnemonic name

---

cmd/devices-api/autopi_clear_vin.go
internal/controllers/nft_controller.go
internal/controllers/user_devices_controller.go
internal/controllers/user_devices_controller_test.go
internal/services/autopi/integration.go
internal/services/autopi_api_service.go

when update name also set it in autopi

PLA-1285: bug fix - set name in autopi too

---

cmd/devices-api/api.go
internal/controllers/user_devices_controller.go
internal/controllers/user_devices_controller_test.go
internal/controllers/user_integrations_controller.go
internal/services/autopi/integration.go
internal/services/autopi/integration_test.go
internal/services/models.go

persist protocol from user devices in fromvin endpoint down to udai when integration pairing happens. 
this will allow to add future logic for template picking

PLA-1233 persist protocol

---

internal/controllers/nft_controller.go

PLA-1345 Add device creation date to vehicle metadata

---

internal/controllers/nft_controller.go

Move AM NFT name to top level, add description

---

internal/services/contracts_events_consumer.go
internal/services/contracts_events_consumer_test.go

Remove returned error for non Aftermarket events and change error message for contract processing

Remove wrong messaging from contracts events listener

---

internal/controllers/device_data_controller.go

PLA-1374 start by just validating minimum value for fuel percent

---

internal/controllers/device_data_controller.go
internal/controllers/device_data_controller_test.go
internal/controllers/nft_controller.go

should fix issue of sharing Tim had noticed

PLA-1383: refactor calculate range so it can be used from two controllers

---

internal/controllers/nft_controller.go
internal/services/contracts_events_consumer.go
migrations/20230425215537_dcn.sql
models/dcn.go

PLA-1347 fix node_id db length n naming

---

cmd/devices-api/api.go
internal/controllers/user_devices_controller.go

- port more endpoints to use userdevice middleware

PLA-1379-port-endpoints

---

internal/services/contracts_events_consumer.go

change due to `name` vs `name_`

PLA-1344 custom struct for DCN name change

---

internal/controllers/user_integrations_controller.go

add beneficiary address to AutoPiDeviceInfo (`/autopi/unit/:unitID`)

add beneficiary addr to AutoPiDeviceInfo

---

internal/controllers/user_devices_controller.go
internal/controllers/user_integrations_controller.go
internal/services/smartcar_client.go

Print more detail: code, request id, body

PLA-1371 Take over Smartcar auth code exchange

---

go.mod
go.sum
internal/api/user_devices.go
internal/controllers/user_devices_controller.go
internal/controllers/user_devices_controller_test.go
internal/services/device_definitions_service.go
internal/services/device_status_ingest_service_test.go
internal/services/mocks/device_definitions_service_mock.go
internal/services/mocks/smartcar_client_mock.go
internal/services/smartcar_client.go

- send the known model and year to vin decode
- vin decode expected to know make from WMI in VIN

PLA-1396 Get known info from SC for decode

---

go.mod
go.sum
internal/services/contracts_events_consumer.go
internal/services/contracts_events_consumer_test.go

Clear out privileges when vehicle transfer event is recieved

---

internal/api/user_devices.go

- update valuation percent growth formula to be relative change
- also applied this change to `GetClaimedVehiclesGrowth` which wasn't where we were seeing the issue but I noticed this growth percentage also wasn't using the relative change formula

PLA-1393-valuation-pct-growth

---

internal/api/user_devices.go

Pla 1393 valuation pct growth

---

cmd/devices-api/api.go
go.mod
go.sum
internal/appmetrics/counters.go
internal/middleware/metrics/grpc_middleware_metric.go
internal/middleware/metrics/http_middleware_metric.go

PLA-1343 - GRPC and HTTP metrics

---

internal/controllers/user_integrations_controller_test.go

Stop checking for device definition correction for Smartcar

---

internal/api/user_devices.go
internal/services/device_status_ingest_service_test.go

-  add vincario metadata to valuation calculus

[EXP-417] add vincario metadata to valuation calculus

---

internal/api/user_devices.go

[EXP-429] remove unnecessary comma

---

internal/api/user_devices.go

issue is that postgres does not return uppercase and the "as" had an uppercase character which was also expected in the property binder.

FIx valuations property binding

---

go.mod
go.sum
internal/services/device_status_ingest_service.go

too many selects on same data causing DB issues, add just an in memory cache to ease the pain for now

Cache the ingest data in memory

---

internal/controllers/nft_controller.go

set content type of vc cred before returning

vc-cred-content-type

---

internal/controllers/device_data_controller_test.go

Fix failing tests

---

internal/services/openai.go

Change error message for openAI

---

internal/services/openai.go

Fix issue with short ChatGpt responses

---

internal/middleware/owner/owner.go
internal/middleware/owner/owner_test.go

- Fix tests in AutoPi owner middleware so they pass
- Change vehicle nft query in ap owner middleware to use autopi vehicle token id

AutoPi Owner Middleware Tests

---

cmd/devices-api/api.go
internal/controllers/device_data_controller.go
internal/controllers/user_integrations_controller.go

Remove more userId checks

---

internal/services/openai.go

Fix panic issue when parsing OpenAI response

---

internal/controllers/device_data_controller.go

- if odometer is less than 100 do not return b/c likely bad data
- logic encapsulated in func

PRO-1498 validate odometer before returning

---

internal/controllers/device_data_controller.go

PRO-1498 add more bad odo's

---

internal/services/issuer/verifible_credential.go
migrations/20230606155413_add_vc_creation_and_exp_date.sql

- By default, generate VIN VCs with an expiration 7 days into the future
- Store the time of the issuance and the time of expiry along with the credential

PRO-1547-expiring-vin-vc

---

internal/controllers/user_integrations_controller.go
internal/controllers/user_integrations_controller_test.go

handle situation where release version may start with v or not

---

internal/contracts/registry.go
internal/controllers/synthetic_devices_controller.go
internal/controllers/synthetic_devices_controller_test.go
internal/services/registry/client.go
internal/services/synthetic_device_instance_service.go

Rename virtual to synthetic in contract and implementation and fix tests

---

cmd/devices-api/main.go
internal/services/openai.go

PRO-1598 Use openai functions for openai calls

---

internal/controllers/synthetic_devices_controller.go
internal/controllers/synthetic_devices_controller_test.go

Use vehicleID from request params and remove from body

---

go.mod
internal/controllers/synthetic_devices_controller.go
internal/controllers/user_devices_controller.go
internal/controllers/user_devices_controller_test.go

Remove the last few direct uses of crypto.Ecrecover

---

go.mod
go.sum
internal/controllers/device_data_controller.go
internal/controllers/device_data_controller_test.go
internal/services/device_data_service.go

PRO-1701 update device data deps and return device snapshot

---

internal/services/registry/storage.go

Actually stop jobs when burning

---

internal/controllers/user_integrations_controller.go
internal/controllers/user_integrations_controller_test.go

PRO-1649 check for sc test vin, with unit test

---

internal/controllers/user_integrations_controller.go

- add valuation call for Tesla devices

[PRO-1745] add valuation call for Tesla devices

---

internal/controllers/device_data_controller.go
internal/controllers/helpers/handlers.go
internal/controllers/nft_controller.go

Check for skipErrorLog

---

internal/services/device_status_ingest_service.go
internal/services/fingerprint/consumer.go

Throw a named error when data.vin = nil

---

internal/controllers/geofences_controller.go
internal/controllers/user_devices_controller.go
internal/controllers/user_devices_controller_test.go

MOB-793 autopi handle duplicate VIN for same user

---

internal/constants/countries_regions.json

Turkey added to Europe region so rest of logic continues to work when we check for europe.

PRO-1698 Add turkey but in eur region

---

internal/services/contracts_events_consumer.go

Listen for registry's AftermarketDeviceClaimed and set owner

---

cmd/devices-api/api.go
cmd/devices-api/main.go
internal/services/contracts_events_consumer.go
internal/services/contracts_events_consumer_test.go
internal/services/macaron/integration.go

Start mac pair

---

internal/services/contracts_events_consumer.go

Pro 1894 macaron mint

---

cmd/devices-api/populate_powertrain.go
internal/constants/consts.go
internal/controllers/user_devices_controller.go
internal/controllers/user_devices_controller_test.go
internal/services/device_definitions_service.go
internal/services/mocks/device_definitions_service_mock.go

PRO-1881 - User - devices - on create

---

internal/services/contracts_events_consumer.go

Store mfr id

---

cmd/devices-api/update_autopi_state.go
internal/controllers/user_devices_controller.go
internal/controllers/user_devices_controller_test.go
internal/services/autopi_api_service.go
internal/services/autopi_api_service_test.go

SM-46 set call name with mmy and unique aspect

---

internal/services/contracts_events_consumer.go

SI-1729 Handle burn

---

internal/config/settings.go
internal/controllers/nft_controller.go

* New environment variable MACARON_NFT_IMAGE
* Switch on the manufacturer token id

SI-2056 Different images for Macaron NFTs

---

internal/services/contracts_events_consumer.go

Code previously assumed that only AutoPis existed. Imitate the logic from pairing.

Handle Macaron unpairs

---

cmd/devices-api/sync_device_templates.go

- ability to apply only one target template

SM-257 implement filtering down to specific template to apply, cleanup

---

internal/controllers/webhooks_controller.go

Validate integration status

---

internal/controllers/synthetic_devices_controller.go
internal/controllers/user_integrations_controller.go

Block Tesla integration if there are any existing integrations

---

internal/appmetrics/counters.go
internal/services/fingerprint/consumer.go

SM-270 - fingerprint ingest

---

internal/controllers/webhooks_controller.go
internal/services/fingerprint/consumer.go

Disable the issuer for a bit, it always fails

---

internal/services/fingerprint/consumer.go

SM-273 Macaron Fingerprinting

---

internal/controllers/user_devices_controller.go
internal/controllers/user_integrations_controller.go

Searched for lines with fiber.NewError and AutoPi

Try to remove AutoPi from error messages for Macarons

---

internal/services/fingerprint/consumer.go
internal/services/fingerprint/consumer_test.go

SM-301 have different methods to extract vin/protocol depending

---

internal/constants/countries_regions.json

Add country: Chile

---

internal/services/fingerprint/consumer_test.go

SM-306 Unit tests for Extract methods for macaron type 1

---

internal/constants/countries_regions.json

lora region yev

---

internal/controllers/user_integrations_controller.go
internal/controllers/user_integrations_controller_test.go
internal/test/helpers.go

* Special error message if burning is in progress.
* Somewhat annoyingly have to look up the right token id.
* ~~Need to write a test.~~

SI-1632 Block integration deletion if synthetic present

---

internal/constants/countries_regions.json

Add Gibraltar (GIB) to Europe region

---

internal/controllers/user_integrations_controller.go

Wrap POST /pair in a transaction

---

cmd/devices-api/dependency_injection.go
internal/controllers/geofences_controller.go
internal/services/fingerprint/consumer_test.go
internal/test/helpers.go

Mostly naming and unused parameters

Fix linter errors

---

cmd/devices-api/api.go
internal/controllers/user_integrations_auth_controller.go
internal/controllers/user_integrations_auth_controller_test.go

Persist auth response from tesla to redis and write tests for new function

---

internal/controllers/user_integrations_controller.go
internal/controllers/user_integrations_controller_test.go
internal/services/autopi_api_service.go
internal/services/mocks/tesla_task_service_mock.go
internal/services/tesla_task_service.go

Add region to TeslaCredentials published to kafka

---

charts/devices-api/values-prod.yaml
charts/devices-api/values.yaml
internal/config/settings.go
internal/services/tesla_fleet_api_service.go
settings.sample.yaml

Update environment variables

---

internal/controllers/user_devices_controller.go

- add handler to logs for register so can more easily find these errors
- return more errors as fiber.NewError so that the client gets the error message

SM-679 changes to better find possible issu

---

internal/controllers/device_data_controller.go
internal/controllers/device_data_controller_test.go

SM-694 add .utc() and log next available time

---

internal/controllers/nft_controller.go

- left TODO's for others that have more context, but for now doesn't seem to make sense to log these things

SM-692 filter out logging image NFT not found and transparent version not set

---

internal/services/contracts_events_consumer.go

Delete autopi specific logic in Minting.
AftermarketDeviceMinted Event

Remove autopi specific logic

---

cmd/devices-api/api.go
internal/controllers/nft_controller.go

SI-2471-post-burn-vehicle

---

cmd/devices-api/api.go
internal/controllers/nft_controller.go

Si 2471 post burn vehicle

---

internal/services/registry/client.go

SI-2471-burn-vehicle-client

---

internal/controllers/user_devices_controller.go

manually block all kia from smartcar connect

---

internal/controllers/user_devices_controller.go
internal/controllers/user_integrations_controller.go

existing kias can register, block new kias minting

---

internal/controllers/synthetic_devices_controller.go
internal/controllers/synthetic_devices_controller_test.go
internal/controllers/user_devices_controller.go

block-new-kias-in-mint-POST

---

docs/docs.go
docs/swagger.json
docs/swagger.yaml
go.mod
internal/controllers/nft_controller.go
internal/controllers/nft_controller_test.go

Minor vehicle burn simplifications

---

cmd/devices-api/api.go
docs/docs.go
docs/swagger.json
docs/swagger.yaml
internal/controllers/user_integrations_controller.go
internal/controllers/user_integrations_controller_test.go

Try to get AutoPi-specific language out of aftemarket handlers

---

docs/docs.go
docs/swagger.json
docs/swagger.yaml
internal/controllers/user_integrations_controller.go
internal/controllers/user_integrations_controller_test.go
internal/services/mocks/tesla_fleet_api_service_mock.go
internal/services/smartcar_client.go
internal/services/tesla_fleet_api_service.go
internal/services/tesla_service.go

More tesla cleanup

---

cmd/devices-api/api.go
cmd/devices-api/web2_pair_sub_command.go
internal/services/autopi/integration.go
internal/services/autopi/integration_test.go

It wasn't being used anywhere. It's unclear how these tests were passing

Remove AutoPiTaskService from the AutoPi transaction handler

---

internal/controllers/synthetic_devices_controller.go
internal/controllers/user_integrations_controller.go

Fix “already exact same pairing” check

---

charts/devices-api/values.yaml
cmd/devices-api/main.go
cmd/devices-api/populate_sd_info_topic.go
internal/config/settings.go

Script for populating table.task.synthetic.fill

---

internal/controllers/user_devices_controller.go

Remove all environment flagging for mint-with-definition

---

internal/controllers/user_devices_controller.go
internal/controllers/user_integrations_controller.go

SM-483 set unpaired on delete integration

---

cmd/devices-api/api.go
docs/docs.go
docs/swagger.json
docs/swagger.yaml
internal/controllers/nft_controller.go
internal/utils/utils.go

Metadata handler for synthetic devices

---

internal/controllers/user_integrations_auth_controller.go
internal/controllers/user_integrations_controller.go
internal/controllers/user_integrations_controller_test.go
internal/services/mocks/tesla_fleet_api_service_mock.go
internal/services/tesla_fleet_api_service.go

Detect available Fleet API commands from the JWT scopes

---

internal/controllers/user_devices_controller.go
internal/controllers/user_devices_controller_test.go
internal/controllers/user_integrations_controller.go

More transactions

---

internal/controllers/device_data_controller.go
internal/controllers/device_data_controller_test.go

- if fuel in percent form divide by 100, add test

fix calculate range for percent fuel

---

.github/workflows/generate.yml
.github/workflows/lint.yml
.github/workflows/test.yml
go.mod
resources/docker/Dockerfile
resources/docker/Dockerfile.cgo

Update to Go 1.22

---

cmd/devices-api/sync_user_device_definition.go

[SM-857] update ud-dd sync script

---

cmd/devices-api/api.go
cmd/devices-api/sync_device_templates.go
cmd/devices-api/sync_user_device_definition.go
internal/controllers/user_devices_controller.go
internal/controllers/user_integrations_controller.go
internal/rpc/user_devices.go
internal/services/device_data_service.go
internal/services/device_definition_integration_service.go
internal/services/device_definitions_service.go
internal/services/synthetic_device_instance_service.go
internal/services/tesla_fleet_api_service.go

More clean 1

---

internal/rpc/user_devices.go

unveriyf vin instead of delete vehicle

---

internal/services/user_device_service.go

Stop checking for email

---

charts/devices-api/templates/secret.yaml
internal/config/settings.go
internal/contracts/signature/signature.go
internal/controllers/user_devices_controller.go

Try EIP-1271

---

internal/controllers/synthetic_devices_controller.go
internal/controllers/synthetic_devices_controller_test.go
internal/controllers/user_devices_controller.go

Actually enabled these, along with mint vehicle, to continue to the chain

Migrate SD mint and SD burn to ERC-1271

---

cmd/devices-api/api.go
docs/docs.go
docs/swagger.json
docs/swagger.yaml
internal/controllers/user_devices_controller.go
internal/controllers/user_devices_controller_test.go

Removing set name endpoint. Can be merged after waas release.
udOwner.Patch("/name", userDeviceController.UpdateName)

Remove name setting route Feature/AS-3035

---

cmd/devices-api/api.go
docs/docs.go
docs/swagger.json
docs/swagger.yaml
internal/controllers/nft_controller.go
internal/controllers/user_devices_controller.go
internal/controllers/user_devices_controller_test.go

Restore old /vin endpoint

---

cmd/devices-api/sync_device_templates.go
internal/controllers/cred_store_mock_test.go
internal/controllers/synthetic_devices_controller_test.go
internal/services/autopi_api_service.go
internal/services/contract_events_consumer_mocks_test.go
internal/services/mocks/autopi_api_service_mock.go
internal/services/mocks/device_data_service_mock.go
internal/services/mocks/device_definition_integration_service_mock.go
internal/services/mocks/device_definition_registrar_mock.go
internal/services/mocks/device_definitions_service_mock.go
internal/services/mocks/event_service_mock.go
internal/services/mocks/ingest_registrar_mock.go
internal/services/mocks/smartcar_client_mock.go
internal/services/mocks/smartcar_task_service_mock.go
internal/services/mocks/tesla_fleet_api_service_mock.go
internal/services/mocks/tesla_service_mock.go
internal/services/mocks/tesla_task_service_mock.go
internal/services/mocks/user_device_service_mock.go
internal/services/smartcar_client.go
internal/services/user_device_service_test.go
pkg/grpc/user_devices.pb.go

- ap script to move remaining laggard devices to tmpl 130
- this may set off alarm on certain cars that are finicky

implement move all force script

---

internal/controllers/synthetic_devices_controller.go
internal/controllers/user_devices_controller.go

As 3088 restrict peugeot mints

---

cmd/devices-api/sync_device_templates.go

- option to pass in csv file to process through

implement move from csv file

---

cmd/devices-api/dependency_injection.go

Adapt to new AWS SDK conventions: no more global region

---

internal/controllers/geofences_controller.go
internal/controllers/helpers/handlers.go
internal/controllers/synthetic_devices_controller.go
internal/controllers/user_devices_controller.go
internal/middleware/owner/owner.go

As 3098 short circuit users api address checks if possible 2

---

Makefile
cmd/devices-api/main.go
cmd/devices-api/vin_decode_compare.go
go.mod
go.sum

SM-1239 implement script for vin decode comparison

---

internal/controllers/user_devices_controller.go

Re-insert fixes for /me and /shared

---

internal/controllers/synthetic_devices_controller.go
internal/controllers/user_devices_controller.go

Remove ERC-1271 guards on prod

---

cmd/devices-api/find_old_style_tasks.go
cmd/devices-api/main.go

Add command to examine jobs

---

cmd/devices-api/find_old_style_tasks.go
cmd/devices-api/main.go
internal/services/task_status_listener.go

Null creds failure

---

internal/controllers/user_devices_controller.go

validate country code

---

cmd/devices-api/generate_events.go
cmd/devices-api/populate_es_dd_data.go
cmd/devices-api/remake_device_definition_topics.go
go.mod
go.sum
internal/controllers/device_data_controller_test.go
internal/controllers/geofences_controller.go
internal/controllers/geofences_controller_test.go
internal/controllers/nft_controller_test.go
internal/controllers/synthetic_devices_controller_test.go
internal/controllers/user_devices_controller.go
internal/controllers/user_devices_controller_test.go
internal/controllers/user_integrations_controller_test.go
internal/services/device_definitions_service.go
internal/services/device_definitions_service_mock.go
internal/services/mocks/device_definitions_service_mock.go
internal/services/user_device_service_test.go
internal/test/helpers.go

remove old get dd by id endpoint

---

charts/devices-api/values-prod.yaml
charts/devices-api/values.yaml
internal/config/settings.go
internal/controllers/user_devices_controller.go

Update Ruptela connectionId address to use the new on chain NFT addr.
Added placeholders for other sources as well.

Add handling for real ch connection Ids

---

docs/docs.go
docs/swagger.json
docs/swagger.yaml
internal/controllers/nft_controller.go
internal/controllers/user_devices_controller.go
internal/controllers/user_integrations_controller.go

- Allow VIN to be changed. I think this should be fine since this is not the source of truth for VIN anymore.

INTG-1453: allow VIN to change if different

---

cmd/devices-api/check_virtual_keys.go
cmd/devices-api/main.go

Subcommand check-virtual-key to check who has virtual keys

---

internal/controllers/user_devices_controller.go
internal/controllers/user_devices_controller_test.go
internal/controllers/user_integrations_controller.go
internal/controllers/user_integrations_controller_test.go
internal/services/mocks/user_device_service_mock.go
internal/services/user_device_service.go

- fix tests due to changes in /fromsmartcar endpoint
- refactor out some things to service so can be mocked
DO NOT MERGE until after break, since there could be breaking changes.

Fix tests for /fromsmartcar

---

internal/controllers/user_devices_controller.go

This update has the active status check query both the old and the new source in clickhouse.

Update active status check to use multiple sources

---

internal/controllers/user_devices_controller.go

Use WhereIn function instead of where

Use whereIn

---

docs/docs.go
docs/swagger.json
docs/swagger.yaml
internal/controllers/user_integrations_controller.go

Ex 3262 return tesla missing scopes

---

cmd/devices-api/enable_telemetry.go

This will remove the configuration

Add a devices-api enable-telemetry delete userDeviceId variant

---

docker-compose.yml
internal/test/helpers.go

Upgrade to postgres 16.6

---

charts/devices-api/values.yaml
cmd/devices-api/migrate.go
go.mod
go.sum
internal/test/helpers.go

Add SSLMode setting

---

charts/devices-api/templates/secret.yaml
cmd/devices-api/api.go
docs/docs.go
docs/swagger.json
docs/swagger.yaml
internal/config/settings.go
internal/controllers/user_devices_controller.go
internal/middleware/psk_auth.go

INTG-1518 implement psk endpoint for compass lookup

---

internal/controllers/user_devices_controller.go
internal/controllers/user_devices_controller_test.go

add tests and fix conflict case for fromvin and compass lookup by vin

---

docs/docs.go
docs/swagger.json
docs/swagger.yaml
internal/controllers/user_devices_controller.go

ex-3370-sacd-minting-params-swagger-update

---

internal/constants/consts.go
internal/controllers/user_integrations_controller.go

INTG-1552 compass support for register

---

internal/controllers/user_devices_controller.go

- added compassIot source and integration

INTG-1543: Compass Iot integration

---

internal/controllers/user_devices_controller.go
internal/controllers/user_devices_controller_test.go

needed a test to make sure it was all working right

add tests around synthetic lookup for compass and fix issue

---

internal/controllers/user_devices_controller.go
internal/services/registry/storage.go

- added compass to storage handler

INTG-1543: added compass to storage handler

---

cmd/devices-api/main.go

fix grpc conn

---

internal/controllers/user_integrations_controller.go
internal/controllers/user_integrations_controller_test.go
internal/services/tesla_fleet_api_service.go

Seem to be getting some false positives on key checks, let's see if this helps without harming the typical case

Try always setting the fleet config and seeing what comes back

---

internal/controllers/user_integrations_controller.go
internal/controllers/user_integrations_controller_test.go
internal/rpc/tesla.go
internal/services/mocks/tesla_fleet_api_service_mock.go
internal/services/models.go
internal/services/tesla_fleet_api_service.go

Hopefully this performs better

Rely on fleet_status to determine whether we should poll

---

cmd/devices-api/check_telemetry.go
internal/controllers/user/sd/sd.go
internal/controllers/user_integrations_controller.go
internal/controllers/user_integrations_controller_test.go

Always try to get discount status and VIN

---

internal/controllers/user_integrations_auth_controller.go

Nicer, 4XX responses when people don't provide auth code or redirect

---

cmd/devices-api/check_telemetry.go
internal/services/tesla_task_service.go

Populate discount status immediately

---

internal/controllers/user_integrations_controller.go
internal/controllers/user_integrations_controller_test.go

Make sure Tesla firmware is at least 2024.26 before trying to set config

---

cmd/devices-api/main.go
go.mod
go.sum
internal/services/cio/cio.go

Use owner address instead of Accounts id for disconnection events

---

cmd/devices-api/api.go
internal/controllers/synthetic_devices_controller.go
internal/controllers/synthetic_devices_controller_test.go

register sd mint with tesla oracle

---

internal/controllers/nft_controller.go

Put in a guard for commands not being present at all

---

internal/controllers/user_devices_controller.go
internal/services/identity_api.go

handle graphql errors, check for tokenId being zero

---

internal/controllers/nft_controller.go
internal/controllers/nft_controller_test.go
internal/controllers/user_devices_controller.go
internal/controllers/user_devices_controller_test.go

INTG-1769: support patch for japan chassis numbers

---

internal/controllers/nft_controller.go
internal/controllers/nft_controller_test.go
internal/services/mocks/device_definitions_service_mock.go
internal/services/mocks/identity_api_mock.go

update logic, add unit test for shorter jp vin

---

internal/services/contracts_events_consumer.go
internal/services/contracts_events_consumer_test.go

If it's unknown then there is nothing we can do anyway.

Stop checking the definition id

---

internal/services/tesla_fleet_api_service.go

This always be turned on come August.

Prefer typed Tesla telemetry

---

internal/controllers/user_devices_controller.go

remove image from mint command requirement

---

internal/controllers/nft_controller.go

improve validation for Update VIN endpoint

---

go.mod
go.sum
internal/controllers/synthetic_devices_controller.go
internal/controllers/synthetic_devices_controller_mock_test.go
internal/controllers/synthetic_devices_controller_test.go
internal/controllers/user_devices_controller.go

Also delete some unused structs

Obtain child number and address from the oracle

---

internal/controllers/user/sd/sd.go
internal/controllers/user_integrations_controller.go

Try to stream in MCU-2 toggle cases

---

internal/controllers/user_devices_controller.go
internal/controllers/user_integrations_controller.go

Don't start Telemetry if the sub is inactive
